file_format: "1"
id: dumbpad
name: dumbpad
type: shield
url: https://github.com/imchipwood/dumbpad/tree/master/combo_oled
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
